CREATE TABLE users
(
  id SERIAL PRIMARY KEY, -- Auto increment 
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
) 

CREATE TABLE categories
(
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES USERS (id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL
)